# Generated by Django 6.0.2 on 2026-03-03 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evo_id', models.CharField(max_length=50, unique=True, verbose_name='ID EVO')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Aluno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(verbose_name='Horário de Entrada')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Horário de Saída')),
                ('is_active', models.BooleanField(default=True, verbose_name='Treino em Andamento')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='evo_integration.member')),
            ],
        ),
    ]
