# Generated by Django 6.0.2 on 2026-03-28 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evo_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('evo_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_on_shift', models.BooleanField(default=False, help_text='Indica se o professor está trabalhando neste turno')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='evo_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='check_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evo_integration.member'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evo_integration.instructor'),
        ),
    ]
