# Generated by Django 6.0.2 on 2026-03-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evo_integration', '0002_instructor_alter_member_evo_id_alter_member_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='max_capacity',
            field=models.IntegerField(default=5, help_text='Limite máximo de alunos simultâneos'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='is_on_shift',
            field=models.BooleanField(default=False, help_text='Online no turno'),
        ),
    ]
